import streamlit as st
import time
import json
import io
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from google import genai
from google.api_core import exceptions
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# --- CONFIGURATION ---
PAGE_TITLE = "Redline AI | Enterprise"
PAGE_ICON = "🏢"

# --- SETUP PAGE ---
st.set_page_config(page_title=PAGE_TITLE, page_icon=PAGE_ICON, layout="centered")

# --- HIDE BRANDING ---
hide_st_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            header {visibility: hidden;}
            </style>
            """
st.markdown(hide_st_style, unsafe_allow_html=True)

# --- LEGAL TEXT (PROFESSIONAL & NEUTRAL) ---
TERMS_OF_USE = """
**1. Service Scope:** Redline AI is an automated data extraction tool designed to assist real estate professionals. It is not a law firm and does not provide legal advice, opinions, or counsel.
**2. Data Privacy & Zero Retention:** We prioritize client confidentiality. Documents uploaded to this system are processed in temporary memory for the sole purpose of analysis and are permanently deleted immediately upon completion. We do not store, archive, or use your data to train our models.
**3. Accuracy & Verification:** This report is generated by artificial intelligence. While designed for high accuracy, it may contain errors, omissions, or hallucinations. This document serves as a preliminary draft and must be verified by a qualified professional against the original lease agreement.
**4. Liability:** By using this service, you agree that you are responsible for the final review of all outputs. Redline AI accepts no liability for financial losses or missed clauses resulting from reliance on this automated report.
"""

# --- HUMAN ERROR TRANSLATOR ---
def translate_error(e):
    err_str = str(e).lower()
    if "11001" in err_str or "connection" in err_str:
        return "🌐 Connection Lost. Please check your internet."
    elif "403" in err_str or "api key" in err_str:
        return "🔑 License Error. Please contact Redline Support."
    elif "429" in err_str:
        return "⏳ System is busy. Please wait 10 seconds and try again."
    elif "pdf" in err_str:
        return "📄 The PDF file appears to be corrupted or password protected."
    elif "valueerror" in err_str and "excel" in err_str:
        return "⚠️ Formatting Error. The report could not be saved to Excel."
    else:
        print(f"CRITICAL ERROR: {err_str}") 
        return "⚠️ An unexpected error occurred. Please refresh and try again."

# --- DATABASE LOGIC ---
def connect_to_sheet():
    try:
        scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
        creds_dict = dict(st.secrets["gcp_service_account"])
        creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
        client = gspread.authorize(creds)
        sheet_url = st.secrets["private_sheet_url"]
        return client.open_by_url(sheet_url).sheet1
    except Exception:
        return None

def check_access(code):
    try:
        sheet = connect_to_sheet()
        if not sheet:
            return "⚠️ Database Connection Failed.", None, None
        records = sheet.get_all_records()
        for row in records:
            if str(row['username']) == code:
                if str(row['active']).upper() != "TRUE":
                    return "❌ Account Deactivated.", None, None
                used = int(row['used'])
                limit = int(row['limit'])
                if used >= limit:
                    return f"⚠️ Monthly Limit Reached ({used}/{limit}).", used, limit
                return "OK", used, limit
        return "❌ Invalid Access Code.", None, None
    except Exception:
        return "⚠️ Database Error. Try again.", None, None

def increment_usage(code):
    try:
        sheet = connect_to_sheet()
        cell = sheet.find(code)
        current_val = int(sheet.cell(cell.row, 2).value)
        sheet.update_cell(cell.row, 2, current_val + 1)
    except:
        pass 

# --- BACKEND LOGIC ---
def get_gemini_client():
    try:
        api_key = st.secrets["GOOGLE_API_KEY"]
        return genai.Client(api_key=api_key)
    except:
        return None

def create_excel_bytes(filename, data):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Redline Analysis"
    
    headers = ["Tenant", "Rent", "Deposit", "Risk Score", "Risk Summary"]
    ws.append(headers)
    
    # SAFE EXTRACTION
    raw_flags = data.get("risk_flags", "None")
    if isinstance(raw_flags, list):
        risk_flags_str = ", ".join([str(flag) for flag in raw_flags])
    else:
        risk_flags_str = str(raw_flags)

    ws.append([
        str(data.get("tenant_name", "N/A")), 
        str(data.get("monthly_rent", "N/A")), 
        str(data.get("security_deposit", "N/A")), 
        str(data.get("risk_score", "0")), 
        risk_flags_str
    ])
    
    # Professional Disclaimer in Excel
    ws.append([])
    ws.append(["NOTE: AI-Generated Draft. Please verify with original document."])
    
    header_fill = PatternFill(start_color="8B0000", end_color="8B0000", fill_type="solid")
    for cell in ws[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center', vertical='center')
    
    ws.column_dimensions['A'].width = 30
    ws.column_dimensions['B'].width = 50
    ws.column_dimensions['E'].width = 100
    
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer

def analyze_lease(uploaded_file):
    client = get_gemini_client()
    if not client: raise Exception("API Key Missing")
    
    with st.spinner("Processing Document..."):
        bytes_data = uploaded_file.getvalue()
        temp_filename = "temp_upload.pdf" 
        with open(temp_filename, "wb") as f:
            f.write(bytes_data)
        cloud_file = client.files.upload(file=temp_filename)

    while cloud_file.state.name == "PROCESSING":
        time.sleep(1)
        cloud_file = client.files.get(name=cloud_file.name)

    if cloud_file.state.name == "FAILED": raise Exception("PDF Syntax Error")

    try:
        sys_prompt = st.secrets["prompts"]["system_instruction"]
    except:
        sys_prompt = "Extract tenant_name, monthly_rent, security_deposit, risk_score, risk_flags. JSON."
    
    data = None
    max_retries = 3
    
    with st.spinner("Generating Analysis..."):
        for attempt in range(max_retries):
            try:
                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=[cloud_file, sys_prompt]
                )
                text = response.text.replace("```json", "").replace("```", "").strip()
                data = json.loads(text)
                break 
            except exceptions.ResourceExhausted:
                time.sleep(5) 
            except Exception as e:
                if attempt == max_retries - 1: raise e
                time.sleep(1)
        
        try:
            client.files.delete(name=cloud_file.name)
        except:
            pass

    if not data: raise Exception("AI could not extract data.")
    return data, create_excel_bytes(uploaded_file.name, data)

# --- FRONTEND UI ---
st.title("🏢 Redline AI | Enterprise")
st.caption("Secure Lease Abstraction Engine")

with st.sidebar:
    st.header("Client Portal")
    password = st.text_input("Access Code", type="password")
    
    status = "WAITING"
    if password:
        status, used, limit = check_access(password)
        if status == "OK":
            st.markdown("---")
            st.markdown(f"**Status:** ✅ Active")
            st.markdown(f"**Quota:** {used} / {limit}")
            st.progress(used / limit)
            st.markdown("---")
            with st.expander("Terms of Use"):
                st.markdown(TERMS_OF_USE)
        else:
            st.error(status)

if password and status == "OK":
    uploaded_file = st.file_uploader("Upload Lease Agreement (PDF)", type=["pdf"])

    if "last_file_id" not in st.session_state:
        st.session_state["last_file_id"] = None
        
    if uploaded_file and uploaded_file.file_id != st.session_state["last_file_id"]:
        st.session_state["last_file_id"] = uploaded_file.file_id
        if "audit_result" in st.session_state:
            del st.session_state["audit_result"]

    if uploaded_file is not None:
        
        # --- PROFESSIONAL AGREEMENT ---
        agree = st.checkbox("I agree to the Terms of Use and Privacy Policy")
        
        if agree:
            if st.button("🚀 Run Analysis (-1 Credit)", type="primary"):
                try:
                    data, excel_file = analyze_lease(uploaded_file)
                    st.session_state["audit_result"] = data
                    st.session_state["audit_excel"] = excel_file
                    increment_usage(password)
                    st.toast("✅ Analysis Complete")
                except Exception as e:
                    st.error(translate_error(e))
        else:
            st.info("Please accept the Terms of Use to proceed.")

        if "audit_result" in st.session_state:
            data = st.session_state["audit_result"]
            excel_bytes = st.session_state["audit_excel"]
            
            st.success("Analysis Complete")
            
            col1, col2, col3 = st.columns(3)
            col1.metric("Risk Score", f"{data.get('risk_score', '0')}/10")
            col2.metric("Monthly Rent", str(data.get("monthly_rent", "N/A"))) 
            col3.metric("Deposit", str(data.get("security_deposit", "N/A")))
            
            st.divider()
            st.caption("Note: This is an AI-generated draft. Please verify all data points.")
            
            st.download_button(
                label="📥 Download Excel Report",
                data=excel_bytes,
                file_name=f"AUDIT_REPORT.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
